apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Techno Tim Homepage

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
      Containers:
        header: true
        style: row
        columns: 4
      DNS:
        header: true
        style: row
        columns: 4
      Network:
        header: true
        style: row
        columns: 4
      Remote Access:
        header: true
        style: row
        columns: 4
      Storage:
        header: true
        style: row
        columns: 4
      Media:
        header: true
        style: row
        columns: 4
      Home Automation:
        header: true
        style: row
        columns: 4
      Other:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: ""
            description: pve1
            widget:
                type: proxmox
                url: ""
                username: ""
                password: ""
                node: xing-01
        - Proxmox:
            icon: proxmox.svg
            href: ""
            description: pve2
            widget:
                type: proxmox
                url: ""
                username: ""
                password: ""
                node: xing-02
        - Proxmox:
            icon: proxmox.svg
            href: ""
            description: pve2
            widget:
                type: proxmox
                url: ""
                username: ""
                password: ""
                node: xing-03
        - Proxmox:
            icon: proxmox.svg
            href: ""
            description: pve4
            widget:
                type: proxmox
                url: ""
                username: ""
                password: ""
                node: storinator
    - Containers:
        - Rancher:
            icon: rancher.svg
            href: ""
            description: k8s
        - Longhorn:
            icon: longhorn.svg
            href: ""
            description: k8s storage
        - Portainer:
            icon: portainer.svg
            href: ""
            description: docker
            widget:
                type: portainer
                url: ""
                env: 2
                key: ""
    - DNS:
        - Pi-Hole1:
            icon: pi-hole.svg
            href: ""
            description: quasar
            widget:
                type: pihole
                url: ""
                key: ""
        - Pi-Hole2:
            icon: pi-hole.svg
            href: ""
            description: blazar
            widget:
                type: pihole
                url: ""
                key: ""
        - Pi-Hole3:
            icon: pi-hole.svg
            href: ""
            description: electron
            widget:
                type: pihole
                url: ""
                key: ""
    - Network:
        - UniFi:
            icon: unifi.svg
            href: ""
            description: network
            widget:
                type: unifi
                url: ""
                username: ""
                password: ""
        - Uptime Kuma:
            icon: uptime-kuma.svg
            href: ""
            description: internal
            widget:
                type: uptimekuma
                url: ""
                slug: home
        - Uptime Robot:
            icon: https://play-lh.googleusercontent.com/cUrv0t00FYQ1GKLuOTvv8qjo1lSDjqZC16IOp3Fb6ijew6Br5m4o16HhDp0GBu_Bw8Y=w240-h480-rw
            href: https://uptimerobot.com/dashboard
            description: external
            widget:
                type: uptimerobot
                url: https://api.uptimerobot.com
                key: ""
    - Storage:
        - TrueNAS:
            icon: truenas.svg
            href: ""
            description: scale
            widget:
                type: truenas
                url: ""
                key: ""
        - MinIO:
            icon: minio.svg
            href: ""
            description: object storage
    - Media:
        - Plex:
            icon: plex.svg
            href: ""
            description: media server
            widget:
                type: plex
                url: ""
                key: ""
        - Tautulla:
            icon: tautulli.svg
            href: ""
            description: plex stats
            widget:
                type: tautulli
                url: ""
                key: ""
        - HDHomerun:
            icon: hdhomerun.png
            href: ""
            description: flex 4k
            widget:
                type: hdhomerun
                url: ""
    - Remote Access:
        - PiKVM:
            icon: https://avatars.githubusercontent.com/u/41749659?s=200&v=4
            href: ""
            description: remote kvm
        - IPMI:
            icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
            href: ""
            description: storinator
        - IPMI:
            icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
            href: ""
            description: hl15
        - Netboot:
            icon: https://netboot.xyz/img/nbxyz-laptop.gif
            href: ""
            description: network boot utility
        - Tripp Lite:
            icon: https://upload.wikimedia.org/wikipedia/commons/f/f9/Tripp_Lite_logo.svg
            href: ""
            description: 1500
        - Eaton:
            icon: https://cdn11.bigcommerce.com/s-fg272t4iw0/images/stencil/1280x1280/products/2549/2802/C-12556__63907.1557814942.jpg?c=2
            href: ""
            description: 5p
    - Home Automation:
        - Home Assistant:
            icon: home-assistant.svg
            href: ""
            description: home
            widget:
                type: homeassistant
                url: ""
                key: ""
        - UniFi:
            icon: https://play-lh.googleusercontent.com/DmgQvSdocOrGr0D0rxSBE9sqh23Fw3ck3BgKRN788cZnOKgcZlcEAFRYwmUbp6vMTVI
            href: ""
            description: protect
        - Scryped:
            icon: https://www.scrypted.app/images/web_hi_res_512.png
            href: ""
            description: mgmt console
        - Broadlink Control:
            icon: https://nwzimg.wezhan.net/contents/sitefiles3606/18030899/images/5430245.png
            href: ""
            description: light control
    - Other:
        - GitLab:
            icon: gitlab.svg
            href: https://gitlab.com
            description: source code
        - GitHub:
            icon: github.svg
            href: https://github.com
            description: source code
        - Shlink:
            icon: https://shlink.io/images/shlink-logo-blue.svg
            href: ""
            description: dashboard
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""